import type { Company } from '@/types/domain';

export const seedCompanies: Company[] = [
  { id: 'nvda', ticker: 'NVDA', name: 'NVIDIA', industry: 'Semiconductors', overview: 'Accelerated computing leader spanning data-center GPUs, networking, and AI software.', aiSummary: 'Sample AI summary: demand remains anchored by accelerated computing, with execution and supply concentration as key variables.', bullThesis: 'Platform breadth and developer adoption can sustain premium growth.', bearThesis: 'Valuation, customer concentration, and custom silicon could compress expectations.', price: 184.42, dailyChange: 1.86, financials: [{ label: 'Sample revenue', value: '$130.5B' }, { label: 'Sample gross margin', value: '73.0%' }, { label: 'Sample FCF', value: '$60.9B' }] },
  { id: 'meta', ticker: 'META', name: 'Meta Platforms', industry: 'Internet Platforms', overview: 'Global social platforms funded primarily by advertising, with expanding AI infrastructure investment.', aiSummary: 'Sample AI summary: engagement and ad efficiency are resilient while infrastructure spending remains the central debate.', bullThesis: 'AI recommendations can improve engagement and monetization across a massive user base.', bearThesis: 'Heavy capital spending and regulatory pressure may limit operating leverage.', price: 712.18, dailyChange: -0.64, financials: [{ label: 'Sample revenue', value: '$164.5B' }, { label: 'Sample margin', value: '42.0%' }, { label: 'Sample users', value: '3.3B' }] },
  { id: 'msft', ticker: 'MSFT', name: 'Microsoft', industry: 'Software', overview: 'Enterprise software and cloud platform with broad distribution across productivity, infrastructure, and AI.', aiSummary: 'Sample AI summary: cloud demand and AI product distribution reinforce a durable recurring-revenue base.', bullThesis: 'Azure and Copilot can compound through Microsoft’s enterprise distribution.', bearThesis: 'AI infrastructure costs and cloud competition may pressure returns.', price: 526.70, dailyChange: 0.48, financials: [{ label: 'Sample revenue', value: '$245.1B' }, { label: 'Sample cloud mix', value: '44%' }, { label: 'Sample FCF', value: '$74.1B' }] },
  { id: 'googl', ticker: 'GOOGL', name: 'Alphabet', industry: 'Internet Platforms', overview: 'Search, video, cloud, and AI research platform serving consumers and enterprises globally.', aiSummary: 'Sample AI summary: AI changes product surfaces but distribution and infrastructure remain strategic strengths.', bullThesis: 'Search distribution, YouTube, and Cloud provide multiple AI monetization paths.', bearThesis: 'AI-native discovery and antitrust remedies threaten search economics.', price: 201.34, dailyChange: 0.92, financials: [{ label: 'Sample revenue', value: '$350.0B' }, { label: 'Sample cloud margin', value: '17%' }, { label: 'Sample cash', value: '$95B' }] },
  { id: 'amd', ticker: 'AMD', name: 'Advanced Micro Devices', industry: 'Semiconductors', overview: 'High-performance compute supplier across data center, client, gaming, and embedded markets.', aiSummary: 'Sample AI summary: data-center product execution is improving, with software maturity the key adoption constraint.', bullThesis: 'Share gains and AI accelerators create several independent growth vectors.', bearThesis: 'Software ecosystem gaps and strong competitors may cap accelerator adoption.', price: 178.66, dailyChange: 2.14, financials: [{ label: 'Sample revenue', value: '$25.8B' }, { label: 'Sample data center', value: '48%' }, { label: 'Sample margin', value: '53%' }] },
  { id: 'aapl', ticker: 'AAPL', name: 'Apple', industry: 'Consumer Technology', overview: 'Integrated consumer hardware, software, and services ecosystem with a large installed base.', aiSummary: 'Sample AI summary: services durability offsets mature hardware cycles while on-device AI creates optionality.', bullThesis: 'Installed-base loyalty and services can sustain cash generation.', bearThesis: 'Hardware maturity, regulation, and China exposure constrain growth.', price: 219.48, dailyChange: -0.28, financials: [{ label: 'Sample revenue', value: '$391.0B' }, { label: 'Sample services mix', value: '25%' }, { label: 'Sample FCF', value: '$108B' }] },
  { id: 'tsm', ticker: 'TSM', name: 'TSMC', industry: 'Semiconductors', overview: 'Leading pure-play foundry manufacturing advanced chips for global technology companies.', aiSummary: 'Sample AI summary: advanced-node leadership supports pricing power, balanced by geographic concentration.', bullThesis: 'Process leadership and AI demand support utilization and long-duration returns.', bearThesis: 'Geopolitical concentration and high capital intensity remain structural risks.', price: 245.90, dailyChange: 1.21, financials: [{ label: 'Sample revenue', value: '$90.1B' }, { label: 'Sample advanced nodes', value: '69%' }, { label: 'Sample margin', value: '57%' }] },
];

const newsThemes = ['Product roadmap advances', 'Demand signals strengthen', 'Capacity plan updated', 'Partner ecosystem expands', 'Industry outlook shifts'];
const reportThemes = ['Quarterly review', 'Competitive landscape', 'Long-term operating model'];
const timelineThemes = ['Leadership update', 'Platform milestone', 'Investor event'];

export const contentRows = seedCompanies.flatMap((company) => [
  ...newsThemes.map((theme, index) => ({ id: `${company.id}-news-${index}`, companyId: company.id, kind: 'news', title: `${company.name}: ${theme}`, body: `Sample story explaining why ${theme.toLowerCase()} matters to the long-term thesis.`, occurredAt: `2026-07-${String(30 - index).padStart(2, '0')}T09:00:00Z`, importance: index < 2 ? 3 : 1 })),
  ...reportThemes.map((theme, index) => ({ id: `${company.id}-report-${index}`, companyId: company.id, kind: 'report', title: theme, body: `Sample ${theme.toLowerCase()} for ${company.name}, covering evidence, open questions, and thesis impact.`, occurredAt: `2026-0${7 - index}-15T09:00:00Z`, importance: 2 })),
  ...timelineThemes.map((theme, index) => ({ id: `${company.id}-timeline-${index}`, companyId: company.id, kind: 'timeline', title: theme, body: `Sample timeline context for ${company.name}.`, occurredAt: `2026-0${5 + index}-10T09:00:00Z`, importance: 1 })),
  { id: `${company.id}-note-0`, companyId: company.id, kind: 'note', title: 'Open research question', body: `What evidence would change the current ${company.name} thesis?`, occurredAt: '2026-07-28T09:00:00Z', importance: 2 },
  { id: `${company.id}-research-0`, companyId: company.id, kind: 'research', title: 'Research brief', body: `Sample industry structure and competitive positioning notes for ${company.name}.`, occurredAt: '2026-07-24T09:00:00Z', importance: 2 },
  { id: `${company.id}-conversation-0`, companyId: company.id, kind: 'conversation', title: 'Thesis review', body: 'Sample saved conversation placeholder. No AI model was used.', occurredAt: '2026-07-22T09:00:00Z', importance: 1 },
  { id: `${company.id}-event-0`, companyId: company.id, kind: 'event', title: 'Upcoming earnings review', body: `Sample calendar event for ${company.name}.`, occurredAt: '2026-08-15T09:00:00Z', importance: 3 },
] as const);
